// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SourceGeneration.Port.Adapters
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityTemplate : EntityTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 3 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 foreach (string path in _context.Usings) { 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 4 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 5 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 if (_context.Usings.Any()) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 8 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 9 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.NamespacePath));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// ");
            
            #line 12 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameJapanese));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n\tpublic class ");
            
            #line 14 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write(" : IEquatable<");
            
            #line 14 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write(">\r\n\t{\r\n\t\t#region Constructors\r\n\r\n\t\t/// <summary>\r\n\t\t/// ");
            
            #line 19 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameJapanese));
            
            #line default
            #line hidden
            this.Write("を初期化します。\r\n\t\t/// </summary>\r\n");
            
            #line 21 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 foreach (EntityContextProperty property in _context.Properties) { 
            
            #line default
            #line hidden
            this.Write("\t\t/// <param name=\"");
            
            #line 22 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ConstructorParameterName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 22 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyNameJapanese));
            
            #line default
            #line hidden
            this.Write("</param>\r\n");
            
            #line 23 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 24 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 24 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", _context.Properties.Select(x => $"{x.TypeName} {x.ConstructorParameterName}"))));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n");
            
            #line 26 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 foreach (EntityContextProperty property in _context.Properties) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 27 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyNameEnglish));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 27 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ConstructorParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 28 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"		}

		#endregion

        #region Operators

        /// <summary>
        /// オペランドが等しい場合には <c>true</c> を返し、それ以外の場合は <c>false</c> を返します。
        /// </summary>
        /// <param name=""lhs"">左辺</param>
        /// <param name=""rhs"">右辺</param>
        /// <returns>オペランドが等しい場合は、 <c>true</c>。それ以外の場合は、 <c>false</c>。</returns>
        public static bool operator ==(");
            
            #line 41 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write(" lhs, ");
            
            #line 41 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write(@" rhs)
        {
            if (lhs is null) return rhs is null;

            bool result = lhs.Equals(rhs);

            return result;
        }

        /// <summary>
        /// オペランドが等しくない場合には <c>true</c> を返し、それ以外の場合は <c>false</c> を返します。
        /// </summary>
        /// <param name=""lhs"">左辺</param>
        /// <param name=""rhs"">右辺</param>
        /// <returns>オペランドが等しくない場合は、 <c>true</c>。それ以外の場合は、 <c>false</c>。</returns>
        public static bool operator !=(");
            
            #line 56 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write(" lhs, ");
            
            #line 56 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write(" rhs)\r\n        {\r\n            bool result = !(lhs == rhs);\r\n\r\n            return " +
                    "result;\r\n        }\r\n\r\n        #endregion\r\n\r\n\t\t#region Properties\r\n\r\n");
            
            #line 67 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 foreach (EntityContextProperty property in _context.Properties) { 
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// ");
            
            #line 69 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyNameJapanese));
            
            #line default
            #line hidden
            this.Write("を取得します。\r\n\t\t/// </summary>\r\n\t\tpublic ");
            
            #line 71 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 71 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyNameEnglish));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\r\n");
            
            #line 73 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"		#endregion
		
        #region Methods
        
        /// <summary>
        /// 指定されたオブジェクトが現在のオブジェクトと等しいかどうかを判断します。
        /// </summary>
        /// <param name=""obj"">現在のオブジェクトと比較するオブジェクト。</param>
        /// <returns>指定したオブジェクトが現在のオブジェクトと等しい場合は <c>true</c>。それ以外の場合は <c>false</c>。</returns>
        public override bool Equals(object? obj)
        {
            bool result = obj switch
            {
                ");
            
            #line 87 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write(@" other => Equals(other),
                _ => base.Equals(obj),
            };

            return result;
        }

        /// <summary>
        /// 現在のオブジェクトが、同じ型の別のオブジェクトと等しいかどうかを示します。
        /// </summary>
        /// <param name=""other"">このオブジェクトと比較するオブジェクト。</param>
        /// <returns>現在のオブジェクトが <c>other</c> パラメーターと等しい場合は <c>true</c>、それ以外の場合は <c>false</c> です。</returns>
        public bool Equals(");
            
            #line 99 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write("? other)\r\n        {\r\n            if (other is null) return false;\r\n\r\n            " +
                    "bool result = ");
            
            #line 103 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" && ", _context.Properties.Where(property => property.IsPrimaryKey).Select(property => $"{property.PropertyNameEnglish} == other.{property.PropertyNameEnglish}"))));
            
            #line default
            #line hidden
            this.Write(@";

            return result;
        }

        /// <summary>
        /// 既定のハッシュ関数として機能します。
        /// </summary>
        /// <returns>現在のオブジェクトのハッシュ コード。</returns>
        public override int GetHashCode()
        {
            int result = HashCode.Combine(");
            
            #line 114 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", _context.Properties.Where(property => property.IsPrimaryKey).Select(property => property.PropertyNameEnglish))));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            return result;\r\n        }\r\n\r\n        /// <summary>\r\n        ///" +
                    " 現在のオブジェクトを表す文字列を返します。\r\n        /// </summary>\r\n        /// <returns>現在のオブジェクトを表" +
                    "す文字列。</returns>\r\n        public override string ToString()\r\n\t\t{\r\n\t\t\treturn $\"{na" +
                    "meof(");
            
            #line 125 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_context.ClassNameEnglish));
            
            #line default
            #line hidden
            this.Write(")} {{ ");
            
            #line 125 "C:\Users\ma310\source\repos\SourceGeneration\SourceGeneration\Port.Adapters\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", _context.Properties.Select(x => $"{{nameof({x.PropertyNameEnglish})}} = {{{x.PropertyNameEnglish}}}"))));
            
            #line default
            #line hidden
            this.Write(" }}\";\r\n\t\t}\r\n\r\n\t\t#endregion\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class EntityTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
